import type { NextPage } from "next";
import Head from "next/head";

//Components
import Hero from "@components/components/Hero";

import Project from "@components/components/projects/Project";
import ProjectDetails from "@components/components/projects/ProjectDetails";
import ProjectBlocks from "@components/components/projects/ProjectBlocks";

const projects = [
	{
		id: 1,
		projectTitle: "Graft Haus",
		link: "https://www.grafthaus.co.uk",
		testimonial: "Aaron is pretty good",
		testimonialAuthor: "Tony",
		services: ["Web design", "Web development", "Wordpress"],
		details: [
			{
				component: "colors",
				colors: ["red", "blue", "green"],
			},
			{
				component: "image",
				url: "https://www.grafthaus.co.uk/wp-content/uploads/2021/05/Untitled-1.jpg",
			},
			{
				component: "text",
				content: "This is how I did this bit",
			},
		],
	},
	{
		id: 2,
		projectTitle: "Vitfor",
		link: "https://www.vitfor.com",
		testimonial: "Aaron is pretty good",
		testimonialAuthor: "Tamsin",
		services: [
			"Branding",
			"Web App Design",
			"Web design",
			"Web development",
			"Wordpress",
		],
		details: [
			{
				component: "colors",
				colors: ["orange", "pink", "cyan"],
			},
			{
				component: "image",
				url: "https://www.grafthaus.co.uk/wp-content/uploads/2021/05/Untitled-2.jpg",
			},
			{
				component: "image",
				url: "https://www.grafthaus.co.uk/wp-content/uploads/2021/05/Untitled-2.jpg",
			},
			{
				component: "image",
				url: "https://www.grafthaus.co.uk/wp-content/uploads/2021/05/Untitled-2.jpg",
			},
			{
				component: "text",
				content: "This is how I did this bit",
			},
		],
	},
	{
		id: 3,
		projectTitle: "Wayne Anthony's",
		link: "https://www.wayneanthonys.co.uk",
		testimonial: "Yeah ZEN MATE",
		testimonialAuthor: "Wayne",
		services: ["Web design", "Web development", "Wordpress"],
		details: [
			{
				component: "colors",
				colors: ["purple", "gray", "yellow"],
			},
			{
				component: "image",
				url: "https://www.grafthaus.co.uk/wp-content/uploads/2021/05/Untitled-3.jpg",
			},
			{
				component: "text",
				content: "This is how I did this bit",
			},
		],
	},
];

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Aaron Massingham | Online Portfolio 2023</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />

			{projects.map((item, index) => (
				<Project
					key={item.id}
					//height={}
					itemNumber={index}
					itemsTotal={projects.length - 1}
					staticChildren={<ProjectBlocks data={item.details} />}
				>
					<ProjectDetails
						link={item.link}
						index={index + 1}
						testimonial={item.testimonial}
						testimonialAuthor={item.testimonialAuthor}
						projectTitle={item.projectTitle}
						services={item.services}
					/>
				</Project>
			))}
		</>
	);
};

export default Home;
