import type { NextPage } from "next";
import Head from "next/head";

//Components
import Hero from "@components/components/Hero";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Aaron Massingham | Online Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
		</>
	);
};

export default Home;
